{
 "title": "imgproxy",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "⏱︎", "query": "1m,2m,5m,10m,30m,1h" },
   { "name": "application", "query": { "query": "label_values(app)" } },
   { "name": "percentile", "label": "‰", "query": "0.99,0.95,0.75,0.5" },
   { "name": "filter" }
  ]
 },
 "panels": [
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(imgproxy_requests_total{app=\"$application\"}[$__range]))",
     "legendFormat": "Images"
    }
   ]
  },
  {
   "title": "In Progress",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(imgproxy_images_in_progress{app=\"$application\"}[$__range]))",
     "legendFormat": "Images"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(imgproxy_errors_total{app=\"$application\"}[$__range]))",
     "legendFormat": "Images"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(imgproxy_request_duration_seconds_count{app=\"$application\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(rate(imgproxy_errors_total{app=\"$application\"}[$interval]))\n/\n    sum(rate(imgproxy_requests_total{app=\"$application\"}[$interval]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(imgproxy_request_duration_seconds_bucket{app=\"$application\"}[$interval])) by (le)) > 0",
     "legendFormat": "Request"
    },
    {
     "expr": "histogram_quantile($percentile, sum(rate(imgproxy_processing_duration_seconds_bucket{app=\"$application\"}[$interval])) by (le)) > 0",
     "legendFormat": "Processing"
    },
    {
     "expr": "histogram_quantile($percentile, sum(rate(imgproxy_download_duration_seconds_bucket{app=\"$application\"}[$interval])) by (le)) > 0",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(process_network_receive_bytes_total{app=\"$application\"}[$interval]))",
     "legendFormat": "↓ In"
    },
    {
     "expr": "-sum(increase(process_network_transmit_bytes_total{app=\"$application\"}[$interval]))",
     "legendFormat": "↑ Out"
    }
   ]
  }
 ]
}