{
 "title": "NodeJS Resources",
 "description": "Node.js prometheus client basic metrics",
 "tags": [
  "NodeJS",
  "Process"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(target_info{telemetry_sdk_language=\"nodejs\"},namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(target_info{namespace=~\"$namespace\", telemetry_sdk_language=\"nodejs\"},service_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(target_info{namespace=~\"$namespace\", service_name=~\"$app|$service\", telemetry_sdk_language=\"nodejs\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_time{process_cpu_state=\"user\", namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}[$__rate_interval]) * 100",
     "legendFormat": "{{pod}} (User)"
    },
    {
     "expr": "irate(process_cpu_time{process_cpu_state=\"system\", namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}[$__rate_interval]) * 100",
     "legendFormat": "{{pod}} (Sys)"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{system_memory_state=\"used\", namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "Used - {{pod}}"
    },
    {
     "expr": "system_memory_usage{system_memory_state=\"free\", namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "Free - {{pod}}"
    }
   ]
  },
  {
   "title": "System Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_memory_utilization{system_memory_state=\"used\", namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "Used - {{pod}}"
    },
    {
     "expr": "system_memory_utilization{system_memory_state=\"free\", namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "Free - {{pod}}"
    }
   ]
  }
 ]
}