{
 "title": "GoTSRPC v2",
 "tags": [
  "foomo",
  "gotsrpc"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "⏱︎", "query": "1m,3m,5m,10m,30m,1h" },
   {
    "name": "percentile",
    "label": "P",
    "query": "99 : 0.99, 95 : 0.95, 90 : 0.9, 75 : 0.75, 50 : 0.5"
   },
   {
    "name": "namespace",
    "label": "⛴︎",
    "query": {
     "query": "label_values(gotsrpc_execution_duration_seconds_bucket,namespace)"
    }
   },
   {
    "name": "service",
    "label": "⛵︎",
    "query": {
     "query": "label_values(gotsrpc_execution_duration_seconds_bucket{namespace=~\"$namespace\"},service)"
    }
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gotsrpc_execution_duration_seconds_count{namespace=~\"$namespace\", service=~\"$service\"}[$interval])) by (namespace, service, gotsrpc_package, gotsrpc_service, gotsrpc_func)",
     "legendFormat": "{{gotsrpc_package}}.{{gotsrpc_service}}.({{gotsrpc_func}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by(gotsrpc_package, gotsrpc_service, gotsrpc_func) (\n    rate(\n      gotsrpc_execution_duration_seconds_count{\n        namespace=~\"$namespace\",\n        service=\"$service\",\n        gotsprc_error=\"true\"\n      }[$interval]\n    )\n  ) * 100\n  )\n/\n(\n  sum by(gotsrpc_package, gotsrpc_service, gotsrpc_func) (\n    rate(\n      gotsrpc_execution_duration_seconds_count{\n        namespace=~\"$namespace\",\n        service=\"$service\",\n        gotsprc_error=\"false\"\n      }[$interval]\n    )\n  )\n)\nor\n(\n  0\n  *\n  sum by(gotsrpc_package, gotsrpc_service, gotsrpc_func) (\n    rate(\n      gotsrpc_execution_duration_seconds_count{\n        namespace=~\"$namespace\",\n        service=\"$service\",\n        gotsprc_error=\"false\"\n      }[$interval]\n    )\n  )\n) > 0",
     "legendFormat": "{{gotsrpc_package}}.{{gotsrpc_service}}.({{gotsrpc_func}})"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(gotsrpc_execution_duration_seconds_bucket{namespace=~\"$namespace\", service=~\"$service\"}[$interval])) by (le, gotsrpc_package, gotsrpc_service, gotsrpc_func))",
     "legendFormat": "{{gotsrpc_package}}.{{gotsrpc_service}}.({{gotsrpc_func}})"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "filters": [
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service" ]
      },
      {
       "id": "span-name",
       "isCustomValue": true,
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [ "GOTSRPC (.*)" ],
       "valueType": "string"
      },
      {
       "id": "ee7df77b",
       "isCustomValue": false,
       "operator": "=~",
       "scope": "resource",
       "tag": "k8s.namespace.name",
       "value": [ "$namespace" ],
       "valueType": "string"
      }
     ],
     "limit": 10,
     "metricsQueryType": "range",
     "query": "{resource.k8s.namespace.name=~\"$namespace\" && resource.service.name=~\"$service\" && name=~\"GOTSRPC (.*)\"}",
     "tableType": "spans"
    }
   ]
  }
 ]
}