{
 "title": "Foomo HTTP Server",
 "tags": [
  "Foomo",
  "HTTP"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "squadron",
    "query": {
     "query": "label_values(http_server_duration_count,namespace)"
    }
   },
   {
    "name": "container",
    "label": "unit",
    "query": {
     "query": "label_values(http_server_duration_count{namespace=~\"$namespace\"},container)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_duration_count{namespace=~\"$namespace\", container=~\"$container\"},http_server_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Inbound: $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{namespace=~\"$namespace\", container=~\"$container\", http_server_name=~\"$service\"}[$__rate_interval])) by (namespace, container, http_server_name, le)) > 0",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{namespace=~\"$namespace\", container=~\"$container\", http_server_name=~\"$service\"}[$__rate_interval])) by (namespace, container, http_server_name, le)) > 0",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(rate(http_server_duration_bucket{namespace=~\"$namespace\", container=~\"$container\", http_server_name=~\"$service\"} [$__rate_interval])) / sum(rate(http_server_duration_bucket{namespace=~\"$namespace\", container=~\"$container\", http_server_name=~\"$service\"} [$__rate_interval]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{namespace=~\"$namespace\", container=~\"$container\", http_server_name=~\"$service\"}[$__rate_interval])) by (http_status_code)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (rate(http_server_duration_count{namespace=~\"$namespace\", container=~\"$container\", http_server_name=~\"$service\",http_status_code=~\"(4|5).*\"}[$__rate_interval])) / ignoring(http_status_code) group_left sum(rate(http_server_duration_count{namespace=~\"$namespace\", container=~\"$container\", http_server_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  }
 ]
}